ACCESS_TOKEN_PRIVATE_KEY_PATH: "access-refresh-token-keys/access-token-private.key"
ACCESS_TOKEN_PUBLIC_KEY_PATH: "access-refresh-token-keys/access-token-public.key"
REFRESH_TOKEN_PRIVATE_KEY_PATH: "access-refresh-token-keys/refresh-token-private.key"
REFRESH_TOKEN_PUBLIC_KEY_PATH: "access-refresh-token-keys/refresh-token-public.key"

MONGODB_URI: "mongodb+srv://cookmateuser:123456cook1@cookmate.q9emxs0.mongodb.net/?retryWrites=true&w=majority&appName=CookMate"
MONGODB_DATABASE: "CookMate"

GOOGLE_CLIENT_ID: "48838306100-bce4oatjddocn7k7k4q4jlt3frncjga1.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET: "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"
